-- pista_estetica - listas (nomes em português e cores de fábrica do GTA)

Listas = {}

-- Cores de fábrica (ids do GTA), por grupo
Listas.cores = {
    { grupo = 'Clássicas', cores = {
        { 0, 'Black' },
        { 1, 'Graphite' },
        { 2, 'Black Steel' },
        { 3, 'Dark Steel' },
        { 4, 'Silver' },
        { 5, 'Bluish Silver' },
        { 6, 'Rolled Steel' },
        { 7, 'Shadow Silver' },
        { 8, 'Stone Silver' },
        { 9, 'Midnight Silver' },
        { 10, 'Cast Iron Silver' },
        { 11, 'Anhracite Black' },
        { 27, 'Red' },
        { 28, 'Torino Red' },
        { 29, 'Formula Red' },
        { 30, 'Blaze Red' },
        { 31, 'Grace Red' },
        { 32, 'Garnet Red' },
        { 33, 'Sunset Red' },
        { 34, 'Cabernet Red' },
        { 35, 'Candy Red' },
        { 36, 'Sunrise Orange' },
        { 38, 'Orange' },
        { 49, 'Dark Green' },
        { 50, 'Racing Green' },
        { 51, 'Sea Green' },
        { 52, 'Olive Green' },
        { 53, 'Bright Green' },
        { 54, 'Gasoline Green' },
        { 61, 'Galaxy Blue' },
        { 62, 'Dark Blue' },
        { 63, 'Saxon Blue' },
        { 64, 'Blue' },
        { 65, 'Mariner Blue' },
        { 66, 'Harbor Blue' },
        { 67, 'Diamond Blue' },
        { 68, 'Surf Blue' },
        { 69, 'Nautical Blue' },
        { 70, 'Ultra Blue' },
        { 71, 'Schafter Purple' },
        { 72, 'Spinnaker Purple' },
        { 73, 'Racing Blue' },
        { 74, 'Light Blue' },
        { 88, 'Yellow' },
        { 89, 'Race Yellow' },
        { 90, 'Bronze' },
        { 91, 'Dew Yellow' },
        { 92, 'Lime Green' },
        { 94, 'Feltzer Brown' },
        { 95, 'Creeen Brown' },
        { 96, 'Chocolate Brown' },
        { 97, 'Maple Brown' },
        { 98, 'Saddle Brown' },
        { 99, 'Bleached Brown' },
        { 100, 'Moss Brown' },
        { 101, 'Bison Brown' },
        { 102, 'Woodbeech Brown' },
        { 103, 'Beechwood Brown' },
        { 104, 'Sienna Brown' },
        { 105, 'Sandy Brown' },
        { 106, 'Bleached Brown' },
        { 107, 'Cream' },
        { 111, 'Ice White' },
        { 112, 'Frost White' },
        { 135, 'Hot Pink' },
        { 136, 'Salmon Pink' },
        { 137, 'Pfsiter Pink' },
        { 138, 'Bright Orange' },
        { 141, 'Midnight Blue' },
        { 142, 'Midnight Purple' },
        { 143, 'Wine Red' },
        { 145, 'Bright Purple' },
        { 147, 'Carbon Black' },
        { 150, 'Lava Red' },
    } },
    { grupo = 'Foscas', cores = {
        { 12, 'Black' },
        { 13, 'Gray' },
        { 14, 'Light Gray' },
        { 39, 'Red' },
        { 40, 'Dark Red' },
        { 41, 'Orange' },
        { 42, 'Yellow' },
        { 55, 'Lime Green' },
        { 82, 'Dark Blue' },
        { 83, 'Blue' },
        { 84, 'Midnight Blue' },
        { 131, 'Ice White' },
        { 148, 'Schafter Purple' },
        { 149, 'Midnight Purple' },
        { 151, 'Forest Green' },
        { 152, 'Olive Darb' },
        { 153, 'Dark Earth' },
        { 154, 'Desert Tan' },
        { 155, 'Foliage Green' },
    } },
    { grupo = 'Metais', cores = {
        { 117, 'Brushed Steel' },
        { 118, 'Brushed Black Steel' },
        { 119, 'Brushed Aluminum' },
        { 120, 'Chrome' },
        { 158, 'Pure Gold' },
        { 159, 'Brushed Gold' },
    } },
    { grupo = 'Desgastadas', cores = {
        { 21, 'Black' },
        { 22, 'Graphite' },
        { 23, 'Silver Grey' },
        { 24, 'Silver' },
        { 25, 'Blue Silver' },
        { 26, 'Shadow Silver' },
        { 46, 'Red' },
        { 47, 'Golden Red' },
        { 48, 'Dark Red' },
        { 58, 'Dark Green' },
        { 59, 'Green' },
        { 60, 'Sea Wash' },
        { 85, 'Dark blue' },
        { 86, 'Blue' },
        { 87, 'Light blue' },
        { 113, 'Honey Beige' },
        { 114, 'Brown' },
        { 115, 'Dark Brown' },
        { 116, 'straw beige' },
        { 121, 'Off White' },
        { 123, 'Orange' },
        { 124, 'Light Orange' },
        { 126, 'Taxi Yellow' },
        { 130, 'Orange' },
        { 132, 'White' },
        { 133, 'Olive Army Green' },
    } },
    { grupo = 'Camaleão', cores = {
        { 161, 'Anodized Red Pearl' },
        { 162, 'Anodized Wine Pearl' },
        { 163, 'Anodized Purple Pearl' },
        { 164, 'Anodized Blue Pearl' },
        { 165, 'Anodized Green Pearl' },
        { 166, 'Anodized Lime Pearl' },
        { 167, 'Anodized Copper Pearl' },
        { 168, 'Anodized Bronze Pearl' },
        { 169, 'Anodized Champagne Pearl' },
        { 170, 'Anodized Gold Pearl' },
        { 171, 'Green/Blue Flip' },
        { 172, 'Green/Red Flip' },
        { 173, 'Green/Brown Flip' },
        { 174, 'Green/Turquoise Flip' },
        { 175, 'Green/Purple Flip' },
        { 176, 'Teal/Purple Flip' },
        { 177, 'Turquoise/Red Flip' },
        { 178, 'Turquoise/Purple Flip' },
        { 179, 'Cyan/Purple Flip' },
        { 180, 'Blue/Pink Flip' },
        { 181, 'Blue/Green Flip' },
        { 182, 'Purple/Red Flip' },
        { 183, 'Purple/Green Flip' },
        { 184, 'Magenta/Green Flip' },
        { 185, 'Magenta/Yellow Flip' },
        { 186, 'Burgundy/Green Flip' },
        { 187, 'Magenta/Cyan Flip' },
        { 188, 'Copper/Purple Flip' },
        { 189, 'Magenta/Orange Flip' },
        { 190, 'Red/Orange Flip' },
        { 191, 'Orange/Purple Flip' },
        { 192, 'Orange/Blue Flip' },
        { 193, 'White/Purple Flip' },
        { 194, 'Red/Rainbow Flip' },
        { 195, 'Blue/Rainbow Flip' },
        { 196, 'Dark Green Pearl' },
        { 197, 'Dark Teal Pearl' },
        { 198, 'Dark Blue Pearl' },
        { 199, 'Dark Purple Pearl' },
        { 200, 'Oil Slick Pearl' },
        { 201, 'Light Green Pearl' },
        { 202, 'Light Blue Pearl' },
        { 203, 'Light Purple Pearl' },
        { 204, 'Light Pink Pearl' },
        { 205, 'Off White Pearl' },
        { 206, 'Cute Pink Pearl' },
        { 207, 'Baby Yellow Pearl' },
        { 208, 'Baby Green Pearl' },
        { 209, 'Baby Blue Pearl' },
        { 210, 'Cream Pearl' },
        { 211, 'White Prismatic Pearl' },
        { 212, 'Graphite Prismatic Pearl' },
        { 213, 'Blue Prismatic Pearl' },
        { 214, 'Purple Prismatic Pearl' },
        { 215, 'Hot Pink Prismatic Pearl' },
        { 216, 'Red Prismatic Pearl' },
        { 217, 'Green Prismatic Pearl' },
        { 218, 'Black Prismatic Pearl' },
        { 219, 'Oil Spill Prismatic Pearl' },
        { 220, 'Rainbow Prismatic Pearl' },
        { 221, 'Black Holographic Pearl' },
        { 222, 'White Holographic Pearl' },
        { 223, 'Fubuki-jo Specials: Monochrome' },
        { 224, 'Fubuki-jo Specials: Night & Day' },
        { 225, 'Fubuki-jo Specials: The Verlierer' },
        { 226, 'Fubuki-jo Specials: Sprunk Extreme' },
        { 227, 'Fubuki-jo Specials: Vice City' },
        { 228, 'Fubuki-jo Specials: Synthwave Night' },
        { 229, 'Fubuki-jo Specials: Four Seasons' },
        { 230, 'Fubuki-jo Specials: M9 Throwback' },
        { 231, 'Fubuki-jo Specials: Bubblegum' },
        { 232, 'Fubuki-jo Specials: Full Rainbow' },
        { 233, 'Fubuki-jo Specials: Sunset' },
        { 234, 'Fubuki-jo Specials: The Seven' },
        { 235, 'Fubuki-jo Specials: Kamen Rider' },
        { 236, 'Fubuki-jo Specials: Chromatic' },
        { 237, 'Fubuki-jo Specials: It\'s Christmas!' },
        { 238, 'Fubuki-jo Specials: Temperature' },
        { 239, 'Fubuki-jo Specials: HSW Badge' },
        { 240, 'Fubuki-jo Specials: Anod. Lightning' },
        { 241, 'Fubuki-jo Specials: Emeralds' },
        { 242, 'Fubuki-jo Specials: Fubuki Castle' },
    } },
}

-- Buzinas (mod 14)
Listas.buzinas = {
    [0] = 'Truck Horn',
    [1] = 'Cop Horn',
    [2] = 'Clown Horn',
    [3] = 'Musical Horn 1',
    [4] = 'Musical Horn 2',
    [5] = 'Musical Horn 3',
    [6] = 'Musical Horn 4',
    [7] = 'Musical Horn 5',
    [8] = 'Sad Trombone',
    [9] = 'Classical Horn 1',
    [10] = 'Classical Horn 2',
    [11] = 'Classical Horn 3',
    [12] = 'Classical Horn 4',
    [13] = 'Classical Horn 5',
    [14] = 'Classical Horn 6',
    [15] = 'Classical Horn 7',
    [16] = 'Scale - Do',
    [17] = 'Scale - Re',
    [18] = 'Scale - Mi',
    [19] = 'Scale - Fa',
    [20] = 'Scale - Sol',
    [21] = 'Scale - La',
    [22] = 'Scale - Ti',
    [23] = 'Scale - Do',
    [24] = 'Jazz Horn 1',
    [25] = 'Jazz Horn 2',
    [26] = 'Jazz Horn 3',
    [27] = 'Jazz Horn Loop',
    [28] = 'Star Spangled Banner 1',
    [29] = 'Star Spangled Banner 2',
    [30] = 'Star Spangled Banner 3',
    [31] = 'Star Spangled Banner 4',
    [32] = 'Classical Horn 8 Loop',
    [33] = 'Classical Horn 9 Loop',
    [34] = 'Classical Horn 10 Loop',
    [35] = 'Classical Horn 8',
    [36] = 'Classical Horn 9',
    [37] = 'Classical Horn 10',
    [38] = 'Funeral Loop',
    [39] = 'Funeral',
    [40] = 'Spooky Loop',
    [41] = 'Spooky',
    [42] = 'San Andreas Loop',
    [43] = 'San Andreas',
    [44] = 'Liberty City Loop',
    [45] = 'Liberty City',
    [46] = 'Festive 1 Loop',
    [47] = 'Festive 1',
    [48] = 'Festive 2 Loop',
    [49] = 'Festive 2',
    [50] = 'Festive 3 Loop',
    [51] = 'Festive 3',
    [52] = 'Air Horn Low Loop',
    [53] = 'Air Horn Low',
    [54] = 'Air Horn Medium Loop',
    [55] = 'Air Horn Medium',
    [56] = 'Air Horn High Loop',
    [57] = 'Air Horn High',
}

-- Peças (mod do GTA) -> nome
Listas.pecas = {
    [0] = 'Aerofólio', [1] = 'Para-choque dianteiro', [2] = 'Para-choque traseiro', [3] = 'Saias laterais',
    [4] = 'Escapamento', [5] = 'Santo-antônio', [6] = 'Grade', [7] = 'Capô', [8] = 'Para-lama esquerdo',
    [9] = 'Para-lama direito', [10] = 'Teto', [25] = 'Suporte da placa', [26] = 'Placa decorativa',
    [27] = 'Acabamento interno', [28] = 'Enfeites', [29] = 'Painel', [30] = 'Mostradores',
    [31] = 'Alto-falantes das portas', [32] = 'Bancos', [33] = 'Volante', [34] = 'Manopla do câmbio',
    [35] = 'Plaquetas', [36] = 'Som', [37] = 'Porta-malas', [38] = 'Hidráulica', [39] = 'Bloco do motor',
    [40] = 'Filtro de ar', [41] = 'Barras de torre', [42] = 'Caixas de roda', [43] = 'Antenas',
    [44] = 'Acabamento externo', [45] = 'Tanque', [46] = 'Porta esquerda', [47] = 'Porta direita',
    [49] = 'Barra de luz',
}

-- Categorias da oficina de estética: quais peças entram em cada uma e para onde a câmera olha
Listas.categorias = {
    { id = 'frente',   label = 'Dianteira',        camera = 'frente',   mods = { 1, 6, 7, 8, 9 } },
    { id = 'traseira', label = 'Traseira',         camera = 'traseira', mods = { 2, 0, 4, 37 } },
    { id = 'lateral',  label = 'Laterais e teto',  camera = 'lateral',  mods = { 3, 10, 5, 42, 43, 44, 46, 47, 49 } },
    { id = 'rodas',    label = 'Rodas',            camera = 'rodas' },
    { id = 'luzes',    label = 'Neon e faróis',    camera = 'luzes' },
    { id = 'vidros',   label = 'Insulfilm',        camera = 'vidros' },
    { id = 'interior', label = 'Interior',         camera = 'interior', mods = { 27, 29, 30, 31, 32, 33, 34, 35, 36, 28 } },
    { id = 'motor',    label = 'Motor (visual)',   camera = 'motor',    mods = { 39, 40, 41, 45, 38 } },
    { id = 'placa',    label = 'Placa',            camera = 'placa',    mods = { 25, 26 } },
    { id = 'adesivos', label = 'Adesivos',         camera = 'lateral' },
    { id = 'extras',   label = 'Extras',           camera = 'geral' },
    { id = 'buzina',   label = 'Buzina',           camera = 'frente' },
}

Listas.tiposRoda = {
    { 0, 'Esportiva' }, { 1, 'Muscle' }, { 2, 'Lowrider' }, { 3, 'SUV' }, { 4, 'Off-road' },
    { 5, 'Tuner' }, { 7, 'Luxo' }, { 8, "Benny's Original" }, { 9, "Benny's Bespoke" },
    { 10, 'Fórmula' }, { 11, 'Rua' }, { 12, 'Pista' },
}

Listas.xenon = {
    { -1, 'Padrão', '#dfe7f2' }, { 0, 'Branco', '#f4f7ff' }, { 1, 'Azul', '#2a5bff' },
    { 2, 'Azul elétrico', '#2fa6ff' }, { 3, 'Verde menta', '#4dffb0' }, { 4, 'Verde limão', '#9dff3a' },
    { 5, 'Amarelo', '#ffef3a' }, { 6, 'Dourado', '#ffbe2e' }, { 7, 'Laranja', '#ff7a1a' },
    { 8, 'Vermelho', '#ff2a2a' }, { 9, 'Rosa', '#ff6fa8' }, { 10, 'Pink', '#ff2fc0' },
    { 11, 'Roxo', '#8a3bff' }, { 12, 'Luz negra', '#4a1dff' },
}

Listas.neonCores = {
    { 'Branco', 222, 222, 255 }, { 'Azul', 2, 21, 255 }, { 'Azul elétrico', 3, 83, 255 },
    { 'Verde menta', 0, 255, 140 }, { 'Verde limão', 94, 255, 1 }, { 'Amarelo', 255, 255, 0 },
    { 'Dourado', 255, 150, 0 }, { 'Laranja', 255, 62, 0 }, { 'Vermelho', 255, 1, 1 },
    { 'Rosa', 255, 50, 100 }, { 'Pink', 255, 5, 190 }, { 'Roxo', 35, 1, 255 }, { 'Luz negra', 15, 3, 255 },
}

Listas.fumacaCores = {
    { 'Branca', 254, 254, 254 }, { 'Preta', 1, 1, 1 }, { 'Azul', 0, 150, 255 }, { 'Amarela', 255, 255, 50 },
    { 'Laranja', 255, 153, 51 }, { 'Vermelha', 255, 10, 10 }, { 'Verde', 10, 255, 10 },
    { 'Roxa', 153, 10, 153 }, { 'Rosa', 255, 102, 178 }, { 'Cinza', 128, 128, 128 },
}

Listas.insulfilm = {
    { 0, 'Sem insulfilm' }, { 3, 'Fumê claro' }, { 2, 'Fumê escuro' }, { 1, 'Preto total' },
    { 4, 'De fábrica' }, { 5, 'Verde' },
}

Listas.placas = {
    { 0, 'Azul no branco 1' }, { 3, 'Azul no branco 2' }, { 4, 'Azul no branco 3' },
    { 1, 'Amarela no preto' }, { 2, 'Amarela no azul' }, { 5, 'North Yankton' }, { 6, 'eCola' },
    { 7, 'Las Venturas' }, { 8, 'Liberty City' }, { 9, 'LS Car Meet' }, { 10, 'LS Panic' },
    { 11, 'Pounders' }, { 12, 'Sprunk' },
}

Listas.neonLados = { { 0, 'Esquerda' }, { 1, 'Direita' }, { 2, 'Frente' }, { 3, 'Traseira' } }
